In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("retail_sales_dataset.csv")

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Age,Gender,Region,Product_Name,Product_Category,Quantity,Unit_Price,Discount,Sales_Amount,Payment_Method,Customer_Rating
0,ORD100001,2024-04-12,CUST1073,NaN,Female,North,Travel Mug,Accessories,4,854.05,0.00,3416.20,Net Banking,3.0
1,ORD100002,2025-03-11,CUST1017,19.0,Female,East,Laptop Backpack,Accessories,1,1363.95,0.10,1227.56,Credit Card,4.0
2,ORD100003,2024-09-27,CUST1009,28.0,Female,North,Running Shoes,Sports,1,3148.95,0.00,3148.95,UPI,5.0
3,ORD100004,2024-04-16,CUST1143,30.0,Female,East,Denim Jeans,Clothing,2,1799.00,0.05,3418.10,Debit Card,4.0
4,ORD100005,2024-03-12,CUST1152,27.0,Female,South,Office Chair,Furniture,1,7873.95,0.05,7480.25,UPI,4.0

In [3]:
print("Shape:", df.shape)

Shape: (1008, 14)

In [4]:
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Age', 'Gender', 'Region', 'Product_Name', 'Product_Category', 'Quantity', 'Unit_Price', 'Discount', 'Sales_Amount', 'Payment_Method', 'Customer_Rating']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1008 non-null   str
 1   Order_Date        1003 non-null   str
 2   Customer_ID       1008 non-null   str
 3   Customer_Age      993 non-null    float64
 4   Gender            998 non-null    str
 5   Region            1000 non-null   str
 6   Product_Name      1008 non-null   str
 7   Product_Category  1003 non-null   str
 8   Quantity          1008 non-null   int64
 9   Unit_Price        1008 non-null   float64
 10  Discount          996 non-null    float64
 11  Sales_Amount      1008 non-null   float64
 12  Payment_Method    1001 non-null   str
 13  Customer_Rating   997 non-null    float64
dtypes: float64(5), int64(1), str(8)
memory usage: 110.4 KB

In [6]:
df.describe(include='all')

,Order_ID,Order_Date,Customer_ID,Customer_Age,Gender,Region,Product_Name,Product_Category,Quantity,Unit_Price,Discount,Sales_Amount,Payment_Method,Customer_Rating
count,1008,1003,1008,993.000000,998,1000,1008,1003,1008.000000,1008.000000,996.000000,1008.000000,1001,997.000000
unique,1000,533,200,NaN,3,4,15,6,NaN,NaN,NaN,NaN,5,NaN
top,ORD100412,2024-04-08,CUST1029,NaN,Male,South,Office Chair,Electronics,NaN,NaN,NaN,NaN,UPI,NaN
freq,2,8,12,NaN,495,315,81,384,NaN,NaN,NaN,NaN,356,NaN
mean,NaN,NaN,NaN,41.660624,NaN,NaN,NaN,NaN,3.044643,2043.871032,0.070231,5929.594524,NaN,3.819458
std,NaN,NaN,NaN,13.822121,NaN,NaN,NaN,NaN,1.400451,1868.408298,0.061308,6673.998933,NaN,1.117361
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,1.000000,379.050000,0.000000,303.240000,NaN,1.000000
25%,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,2.000000,799.000000,0.000000,1784.110000,NaN,3.000000
50%,NaN,NaN,NaN,42.000000,NaN,NaN,NaN,NaN,3.000000,1519.050000,0.050000,3595.750000,NaN,4.000000
75%,NaN,NaN,NaN,53.000000,NaN,NaN,NaN,NaN,4.000000,2499.000000,0.100000,7195.500000,NaN,5.000000
max,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,5.000000,7873.950000,0.200000,37495.000000,NaN,5.000000

In [7]:
quality_report = pd.DataFrame({
    'Column': df.columns,
    'Null_Count': df.isnull().sum().values,
    'Data_Type': df.dtypes.astype(str).values,
    'Unique_Values': df.nunique().values
})

quality_report

              Column  Null_Count Data_Type  Unique_Values
0           Order_ID           0       str           1000
1         Order_Date           5       str            533
2        Customer_ID           0       str            200
3       Customer_Age          15   float64             48
4             Gender          10       str              3
5             Region           8       str              4
6       Product_Name           0       str             15
7   Product_Category           5       str              6
8           Quantity           0     int64              5
9         Unit_Price           0   float64             45
10          Discount          12   float64              5
11      Sales_Amount           0   float64            565
12    Payment_Method           7       str              5
13   Customer_Rating          11   float64              5

In [8]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 8

In [9]:
df.isnull().sum()

Order_ID             0
Order_Date           5
Customer_ID          0
Customer_Age        15
Gender              10
Region               8
Product_Name         0
Product_Category     5
Quantity             0
Unit_Price           0
Discount            12
Sales_Amount         0
Payment_Method       7
Customer_Rating     11
dtype: int64

In [10]:
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicates removed:", duplicates_before - duplicates_after)

Duplicates removed: 8

In [11]:
df['Gender'] = df['Gender'].replace({
    'male': 'Male',
    'M': 'Male',
    'female': 'Female',
    'F': 'Female'
})

In [12]:
df['Gender'] = df['Gender'].astype(str).str.strip()

In [13]:
df.dtypes

Order_ID                str
Order_Date              str
Customer_ID             str
Customer_Age        float64
Gender                  str
Region                  str
Product_Name            str
Product_Category        str
Quantity              int64
Unit_Price          float64
Discount            float64
Sales_Amount        float64
Payment_Method          str
Customer_Rating     float64
dtype: object

In [15]:
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Age', 'Gender', 'Region', 'Product_Name', 'Product_Category', 'Quantity', 'Unit_Price', 'Discount', 'Sales_Amount', 'Payment_Method', 'Customer_Rating']

In [16]:
print(df.head())

    Order_ID  Order_Date Customer_ID  Customer_Age  Gender Region  \
0  ORD100001  2024-04-12    CUST1073           NaN  Female  North
1  ORD100002  2025-03-11    CUST1017          19.0  Female   East
2  ORD100003  2024-09-27    CUST1009          28.0  Female  North
3  ORD100004  2024-04-16    CUST1143          30.0  Female   East
4  ORD100005  2024-03-12    CUST1152          27.0  Female  South

      Product_Name Product_Category  Quantity  Unit_Price  Discount  \
0       Travel Mug      Accessories         4      854.05      0.00
1  Laptop Backpack      Accessories         1     1363.95      0.10
2    Running Shoes           Sports         1     3148.95      0.00
3      Denim Jeans         Clothing         2     1799.00      0.05
4     Office Chair        Furniture         1     7873.95      0.05

   Sales_Amount Payment_Method  Customer_Rating
0       3416.20    Net Banking              3.0
1       1227.56    Credit Card              4.0
2       3148.95            UPI              5.0
3       3418.10     Debit Card              4.0
4       7480.25            UPI              4.0

In [18]:
# Convert date column to datetime
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    errors='coerce'
)

# Convert ID columns to string
df['Order_ID'] = df['Order_ID'].astype('string')
df['Customer_ID'] = df['Customer_ID'].astype('string')

# Convert numeric columns to numeric dtype
numeric_columns = [
    'Customer_Age',
    'Quantity',
    'Unit_Price',
    'Discount',
    'Sales_Amount',
    'Customer_Rating'
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Check the final data types
print(df.dtypes)

Order_ID                    string
Order_Date          datetime64[us]
Customer_ID                 string
Customer_Age               float64
Gender                         str
Region                         str
Product_Name                   str
Product_Category               str
Quantity                     int64
Unit_Price                 float64
Discount                   float64
Sales_Amount               float64
Payment_Method                 str
Customer_Rating            float64
dtype: object

In [19]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
Order_ID             0
Order_Date           5
Customer_ID          0
Customer_Age        15
Gender              10
Region               8
Product_Name         0
Product_Category     5
Quantity             0
Unit_Price           0
Discount            12
Sales_Amount         0
Payment_Method       7
Customer_Rating     10
dtype: int64

In [20]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Age,Gender,Region,Product_Name,Product_Category,Quantity,Unit_Price,Discount,Sales_Amount,Payment_Method,Customer_Rating
0,ORD100001,2024-04-12,CUST1073,NaN,Female,North,Travel Mug,Accessories,4,854.05,0.00,3416.20,Net Banking,3.0
1,ORD100002,2025-03-11,CUST1017,19.0,Female,East,Laptop Backpack,Accessories,1,1363.95,0.10,1227.56,Credit Card,4.0
2,ORD100003,2024-09-27,CUST1009,28.0,Female,North,Running Shoes,Sports,1,3148.95,0.00,3148.95,UPI,5.0
3,ORD100004,2024-04-16,CUST1143,30.0,Female,East,Denim Jeans,Clothing,2,1799.00,0.05,3418.10,Debit Card,4.0
4,ORD100005,2024-03-12,CUST1152,27.0,Female,South,Office Chair,Furniture,1,7873.95,0.05,7480.25,UPI,4.0

In [21]:
missing_report = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percentage': (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_report

                  Missing_Count  Missing_Percentage
Order_ID                      0                 0.0
Order_Date                    5                 0.5
Customer_ID                   0                 0.0
Customer_Age                 15                 1.5
Gender                       10                 1.0
Region                        8                 0.8
Product_Name                  0                 0.0
Product_Category              5                 0.5
Quantity                      0                 0.0
Unit_Price                    0                 0.0
Discount                     12                 1.2
Sales_Amount                  0                 0.0
Payment_Method                7                 0.7
Customer_Rating              10                 1.0

## Missing Data Handling

Missing values are handled according to the type and meaning of each column.

- `Customer_Age`: Median imputation is used because age is a numerical variable and the median is less affected by extreme values.
- `Customer_Rating`: Median imputation is used because ratings are numerical and the median provides a robust central value.
- Categorical columns such as `Gender`, `Region`, `Product_Name`, `Product_Category`, and `Payment_Method`: Mode imputation is appropriate because these columns contain categories.
- `Order_Date`: Missing dates will be investigated before deciding whether to fill or remove them because dates should not be replaced with an arbitrary numerical average.

In [22]:
missing_report = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percentage': (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_report = missing_report[
    missing_report['Missing_Count'] > 0
]

missing_report

                  Missing_Count  Missing_Percentage
Order_Date                    5                 0.5
Customer_Age                 15                 1.5
Gender                       10                 1.0
Region                        8                 0.8
Product_Category              5                 0.5
Discount                     12                 1.2
Payment_Method                7                 0.7
Customer_Rating              10                 1.0

In [23]:
# Numerical columns: median imputation
numeric_missing = [
    'Customer_Age',
    'Customer_Rating'
]

for col in numeric_missing:
    df[col] = df[col].fillna(df[col].median())


# Categorical columns: mode imputation
categorical_missing = [
    'Gender',
    'Region',
    'Product_Name',
    'Product_Category',
    'Payment_Method'
]

for col in categorical_missing:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [24]:
print("Missing values after treatment:")
print(df.isnull().sum())

Missing values after treatment:
Order_ID             0
Order_Date           5
Customer_ID          0
Customer_Age         0
Gender               0
Region               0
Product_Name         0
Product_Category     0
Quantity             0
Unit_Price           0
Discount            12
Sales_Amount         0
Payment_Method       0
Customer_Rating      0
dtype: int64

In [25]:
duplicates_before = df.duplicated().sum()

print("Duplicate rows before removal:", duplicates_before)

Duplicate rows before removal: 0

In [26]:
df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicate rows after removal:", duplicates_after)
print("Duplicates removed:", duplicates_before - duplicates_after)

Duplicate rows after removal: 0
Duplicates removed: 0

## Standardisation of Categorical Data

Categorical values can contain inconsistent capitalization, spacing, or abbreviations. These inconsistencies can cause the same category to be treated as different values.

The categorical columns are therefore cleaned by:
- Removing leading and trailing spaces
- Standardising capitalization
- Checking unique values before and after cleaning

In [27]:
categorical_columns = [
    'Gender',
    'Region',
    'Product_Name',
    'Product_Category',
    'Payment_Method'
]

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

Gender:
<StringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: str

Region:
<StringArray>
['North', 'East', 'South', 'West']
Length: 4, dtype: str

Product_Name:
<StringArray>
[         'Travel Mug',     'Laptop Backpack',       'Running Shoes',
         'Denim Jeans',        'Office Chair',      'Wireless Mouse',
 'Mechanical Keyboard',         'Smart Watch',           'USB-C Hub',
          'Power Bank',      'Cotton T-Shirt',   'Bluetooth Speaker',
        'Notebook Set',        'Water Bottle',           'Desk Lamp']
Length: 15, dtype: str

Product_Category:
<StringArray>
['Accessories', 'Sports', 'Clothing', 'Furniture', 'Electronics',
 'Stationery']
Length: 6, dtype: str

Payment_Method:
<StringArray>
['Net Banking', 'Credit Card', 'UPI', 'Debit Card', 'Cash']
Length: 5, dtype: str

In [28]:
for col in categorical_columns:
    df[col] = df[col].astype('string').str.strip()

In [29]:
df['Gender'] = df['Gender'].replace({
    'male': 'Male',
    'M': 'Male',
    'MALE': 'Male',
    'female': 'Female',
    'F': 'Female',
    'FEMALE': 'Female'
})

In [30]:
df['Region'] = df['Region'].str.title()

df['Product_Category'] = df['Product_Category'].str.title()

df['Payment_Method'] = df['Payment_Method'].str.title()

df['Product_Name'] = df['Product_Name'].str.title()

In [31]:
for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

Gender:
<StringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: string

Region:
<StringArray>
['North', 'East', 'South', 'West']
Length: 4, dtype: string

Product_Name:
<StringArray>
[         'Travel Mug',     'Laptop Backpack',       'Running Shoes',
         'Denim Jeans',        'Office Chair',      'Wireless Mouse',
 'Mechanical Keyboard',         'Smart Watch',           'Usb-C Hub',
          'Power Bank',      'Cotton T-Shirt',   'Bluetooth Speaker',
        'Notebook Set',        'Water Bottle',           'Desk Lamp']
Length: 15, dtype: string

Product_Category:
<StringArray>
['Accessories', 'Sports', 'Clothing', 'Furniture', 'Electronics',
 'Stationery']
Length: 6, dtype: string

Payment_Method:
<StringArray>
['Net Banking', 'Credit Card', 'Upi', 'Debit Card', 'Cash']
Length: 5, dtype: string

## Standardisation Result

The categorical fields were standardised by removing unnecessary whitespace and applying consistent formatting.

Gender values were mapped to consistent labels such as `Male` and `Female`. Other categorical fields were formatted consistently using title case.

This prevents multiple representations of the same category from being treated as separate values during analysis.

In [32]:
df.dtypes

Order_ID                    string
Order_Date          datetime64[us]
Customer_ID                 string
Customer_Age               float64
Gender                      string
Region                      string
Product_Name                string
Product_Category            string
Quantity                     int64
Unit_Price                 float64
Discount                   float64
Sales_Amount               float64
Payment_Method              string
Customer_Rating            float64
dtype: object

In [33]:
print("Order_ID:", df['Order_ID'].dtype)
print("Order_Date:", df['Order_Date'].dtype)
print("Customer_ID:", df['Customer_ID'].dtype)
print("Customer_Age:", df['Customer_Age'].dtype)
print("Quantity:", df['Quantity'].dtype)
print("Unit_Price:", df['Unit_Price'].dtype)
print("Discount:", df['Discount'].dtype)
print("Sales_Amount:", df['Sales_Amount'].dtype)
print("Customer_Rating:", df['Customer_Rating'].dtype)

Order_ID: string
Order_Date: datetime64[us]
Customer_ID: string
Customer_Age: float64
Quantity: int64
Unit_Price: float64
Discount: float64
Sales_Amount: float64
Customer_Rating: float64

## Outlier Detection Using the IQR Method

Outliers are observations that are unusually high or low compared with the majority of the data.

The Interquartile Range (IQR) method is used to identify potential outliers in numerical columns.

The IQR is calculated as:

IQR = Q3 - Q1

Lower Bound = Q1 - 1.5 × IQR

Upper Bound = Q3 + 1.5 × IQR

Values outside these bounds are considered potential outliers.

In [34]:
numeric_columns = [
    'Customer_Age',
    'Quantity',
    'Unit_Price',
    'Discount',
    'Sales_Amount',
    'Customer_Rating'
]

outlier_report = []

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    outlier_report.append({
        'Column': col,
        'Q1': Q1,
        'Q3': Q3,
        'IQR': IQR,
        'Lower_Bound': lower_bound,
        'Upper_Bound': upper_bound,
        'Outlier_Count': len(outliers)
    })

outlier_report = pd.DataFrame(outlier_report)

outlier_report

,Column,Q1,Q3,IQR,Lower_Bound,Upper_Bound,Outlier_Count
0,Customer_Age,30.00,53.0,23.00,-4.500,87.500,0
1,Quantity,2.00,4.0,2.00,-1.000,7.000,0
2,Unit_Price,799.00,2499.0,1700.00,-1751.000,5049.000,80
3,Discount,0.00,0.1,0.10,-0.150,0.250,0
4,Sales_Amount,1784.11,7195.5,5411.39,-6332.975,15312.585,73
5,Customer_Rating,3.00,5.0,2.00,0.000,8.000,0

## Outlier Treatment Decision

The IQR method identified potential outliers in several numerical variables.

These observations will be retained rather than automatically removed. In a retail sales dataset, unusually high quantities, prices, or sales amounts can represent legitimate business transactions rather than data errors.

Removing valid transactions could lead to loss of useful information and inaccurate business analysis.

Therefore, the identified statistical outliers are retained unless they are confirmed to be data-entry errors.

In [37]:
print("Remaining missing values:")
print(df.isnull().sum())

Remaining missing values:
Order_ID             0
Order_Date           5
Customer_ID          0
Customer_Age         0
Gender               0
Region               0
Product_Name         0
Product_Category     0
Quantity             0
Unit_Price           0
Discount            12
Sales_Amount         0
Payment_Method       0
Customer_Rating      0
dtype: int64

In [38]:
print("Remaining duplicate rows:", df.duplicated().sum())

Remaining duplicate rows: 0

In [39]:
after_rows = len(df)
after_nulls = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()

print("Rows after cleaning:", after_rows)
print("Null values after cleaning:", after_nulls)
print("Duplicates after cleaning:", after_duplicates)

Rows after cleaning: 1000
Null values after cleaning: 17
Duplicates after cleaning: 0

In [41]:
df.head(10)

,Order_ID,Order_Date,Customer_ID,Customer_Age,Gender,Region,Product_Name,Product_Category,Quantity,Unit_Price,Discount,Sales_Amount,Payment_Method,Customer_Rating
0,ORD100001,2024-04-12,CUST1073,42.0,Female,North,Travel Mug,Accessories,4,854.05,0.00,3416.20,Net Banking,3.0
1,ORD100002,2025-03-11,CUST1017,19.0,Female,East,Laptop Backpack,Accessories,1,1363.95,0.10,1227.56,Credit Card,4.0
2,ORD100003,2024-09-27,CUST1009,28.0,Female,North,Running Shoes,Sports,1,3148.95,0.00,3148.95,Upi,5.0
3,ORD100004,2024-04-16,CUST1143,30.0,Female,East,Denim Jeans,Clothing,2,1799.00,0.05,3418.10,Debit Card,4.0
4,ORD100005,2024-03-12,CUST1152,27.0,Female,South,Office Chair,Furniture,1,7873.95,0.05,7480.25,Upi,4.0
5,ORD100006,2025-12-01,CUST1038,31.0,Female,South,Wireless Mouse,Electronics,2,799.00,0.10,1438.20,Credit Card,3.0
6,ORD100007,2024-01-21,CUST1163,35.0,Male,North,Travel Mug,Accessories,5,854.05,0.10,3843.22,Credit Card,2.0
7,ORD100008,2025-09-06,CUST1094,26.0,Male,East,Mechanical Keyboard,Electronics,2,2374.05,0.00,4748.10,Credit Card,5.0
8,ORD100009,2024-05-01,CUST1095,56.0,Female,North,Smart Watch,Electronics,1,4198.95,0.05,3989.00,Cash,2.0
9,ORD100010,2025-04-11,CUST1049,45.0,Female,East,Usb-C Hub,Electronics,5,1573.95,0.10,7082.78,Upi,3.0

In [42]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Customer_Age,Gender,Region,Product_Name,Product_Category,Quantity,Unit_Price,Discount,Sales_Amount,Payment_Method,Customer_Rating
995,ORD100996,2025-10-03,CUST1189,34.0,Male,West,Denim Jeans,Clothing,3,1799.00,0.15,4587.45,Cash,4.0
996,ORD100997,2025-08-18,CUST1024,23.0,Male,West,Travel Mug,Accessories,3,899.00,0.00,2697.00,Credit Card,4.0
997,ORD100998,2024-11-16,CUST1148,50.0,Female,East,Denim Jeans,Clothing,3,1888.95,0.00,5666.85,Upi,4.0
998,ORD100999,2024-11-14,CUST1037,22.0,Male,South,Usb-C Hub,Electronics,2,1499.00,0.00,2998.00,Credit Card,4.0
999,ORD101000,2025-09-04,CUST1004,45.0,Female,North,Desk Lamp,Furniture,4,1199.00,0.15,4076.60,Cash,4.0

In [43]:
df.describe()

,Order_Date,Customer_Age,Quantity,Unit_Price,Discount,Sales_Amount,Customer_Rating
count,995,1000.00000,1000.000000,1000.000000,988.000000,1000.00000,1000.000000
mean,2024-12-25 16:24:07.236181,41.67200,3.043000,2043.635000,0.070445,5924.72361,3.824000
min,2024-01-01 00:00:00,18.00000,1.000000,379.050000,0.000000,303.24000,1.000000
25%,2024-06-16 00:00:00,30.00000,2.000000,799.000000,0.000000,1784.11000,3.000000
50%,2024-12-30 00:00:00,42.00000,3.000000,1519.050000,0.050000,3595.75000,4.000000
75%,2025-07-02 00:00:00,53.00000,4.000000,2499.000000,0.100000,7195.50000,5.000000
max,2025-12-30 00:00:00,65.00000,5.000000,7873.950000,0.200000,37495.00000,5.000000
std,NaN,13.73627,1.400397,1865.249792,0.061243,6671.88931,1.112772

In [44]:
print("Order_Date dtype:", df['Order_Date'].dtype)

Order_Date dtype: datetime64[us]

In [45]:
print("Order_ID dtype:", df['Order_ID'].dtype)
print("Customer_ID dtype:", df['Customer_ID'].dtype)

Order_ID dtype: string
Customer_ID dtype: string

In [46]:
output_file = "cleaned_retail_sales_dataset.csv"

df.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File name:", output_file)

Cleaned dataset saved successfully!
File name: cleaned_retail_sales_dataset.csv

In [47]:
import os

print(os.path.abspath(output_file))
print("File exists:", os.path.exists(output_file))

C:\Users\SHAIK.SAMAD\cleaned_retail_sales_dataset.csv
File exists: True

# Conclusion

The dataset was systematically cleaned and transformed into an analysis-ready dataset.

The cleaning process included:

- Initial data-quality assessment
- Missing-value identification and appropriate imputation
- Duplicate detection and removal
- Standardisation of categorical values
- Correction of data types
- Outlier detection using the IQR method
- Evaluation and documentation of outlier treatment
- Before-and-after data-quality comparison
- Final validation of the cleaned dataset

The cleaned dataset was saved as `cleaned_retail_sales_dataset.csv`.

The resulting dataset is now suitable for further analysis and reporting.